// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvnv5ZFVBPeXvI-p-Dd-gM5JTiKB2fAKc',
    appId: '1:264392477122:web:e9691ff2420daed340ee5b',
    messagingSenderId: '264392477122',
    projectId: 'attendance-3d772',
    authDomain: 'attendance-3d772.firebaseapp.com',
    storageBucket: 'attendance-3d772.appspot.com',
    measurementId: 'G-DBJK5TKCFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlNaqJSivo4qRqQZplBjqF61bBTHdil5s',
    appId: '1:264392477122:android:f35de4709e8c342840ee5b',
    messagingSenderId: '264392477122',
    projectId: 'attendance-3d772',
    storageBucket: 'attendance-3d772.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbJ8GE__kkKW7m6HQJBhFIeAAs9mezKUs',
    appId: '1:264392477122:ios:13e01abb4a48288640ee5b',
    messagingSenderId: '264392477122',
    projectId: 'attendance-3d772',
    storageBucket: 'attendance-3d772.appspot.com',
    iosBundleId: 'com.example.atten',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbJ8GE__kkKW7m6HQJBhFIeAAs9mezKUs',
    appId: '1:264392477122:ios:aea129a8c92ff6bf40ee5b',
    messagingSenderId: '264392477122',
    projectId: 'attendance-3d772',
    storageBucket: 'attendance-3d772.appspot.com',
    iosBundleId: 'com.example.atten.RunnerTests',
  );
}
